package com.studies.movies;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path = "")
@CrossOrigin(origins = "http://localhost:4200")
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MovieRepository movieRepository;

    @GetMapping(path = "/movie")
    public @ResponseBody
    Iterable<Movie> getMovies() {
        return movieRepository.findAll();
    }

    @GetMapping(path = "/movie/{id}")
    public @ResponseBody
    Optional<Movie> getMovieById(@PathVariable Integer id) {
        return movieRepository.findById(id);
    }

}